k_profile_id_key: str = "player/profile_id"
k_1v1_display_option: str = "options/1v1_display_option"
k_team_display_option: str = "options/team_display_option"
k_opt_api_locale: str = "options/api_locale"
k_opt_humanized_time: str = "options/humanized_time"
